### ISSUE TITLE
Running outside of Leiningen

### ISSUE THREAD

**Issue by charlesg3** [cemerick/clojurescript.test#104]
I currently have the test suite working when I run `lein cljsbuild test`, however I am looking to package things up in a way that they can be tested outside of Leininging (e.g. in a docker container).

I have copied the runner script from here: https://github.com/cemerick/clojurescript.test/blob/master/resources/cemerick/cljs/test/runner.js (also tried copying one that was written to /tmp).

Whenever I run it outside of Lein, I get the following error:

```
ReferenceError: Can't find variable: cemerick

  test/runner.js:43 in onError

ERROR: cemerick.cljs.test was not required.

You can resolve this issue by ensuring [cemerick.cljs.test] appears
in the :require clause of your test suite namespaces.
Also make sure that your build has actually included any test files.

  test/runner.js:55 in onError
```

Is there anything special I need to do to run things outside of Lein?

Thanks!

**Comment by cemerick** [comment]
Assuming you have the properly-compiled JS output, you should be able to drop it into the appropriate runner whereever. I frequently run tests w/o lein using the runner scripts.

**Comment by cemerick** [comment]
Sorry for the troubles, but I've deprecated this project. Please see the notice at the top of the repo's README. This is a good thing, fundamentally. :-)
