### ISSUE TITLE
Failure under trivial async case?

### ISSUE THREAD

**Issue by elliot42** [cemerick/clojurescript.test#105]
I have a minimal async case and it's failing with a mysterious error message.

```clj
(deftest ^:async test
  (is true)
  (done))
```

```
$ lein cljsbuild test
...
Testing [my ns here] (async)
Error: No protocol method ReadPort.take! defined for type null:
Error: Assert failed: Can't put nil in on a channel
(not (nil? val))
```

I presume this means something going wrong the `core.async` infrastructure in the background?

(All synchronous cases work fine.)

Environment is:
CLJ 1.7
CLJS 1.7.48
PhantomJS 1.9.8

Any ideas?  Thanks you!

**Comment by elliot42** [comment]
Although apparently this isn't working for me under `cljs.test` either--is PhantomJS just incapable of running async tests?

**Comment by cemerick** [comment]
Sorry for the troubles, but I've deprecated this project. Please see the notice at the top of the repo's README. This is a good thing, fundamentally. :-)

**Comment by elliot42** [comment]
No worries thank you for this project up until now!
