### ISSUE TITLE
Support lein test :only

### ISSUE THREAD

**Issue by JulianBirch** [cemerick/clojurescript.test#108]
At the moment, if you're working on a cljc project and try to run an individual test, you type (e.g.)

```
lein test :only ajax.test.core/composite-format
```

It then runs the test in clj mode, but then all tests in cljs mode.

Apologies if the problem is in another part of the stack...

**Comment by cemerick** [comment]
Sorry for the troubles, but I've deprecated this project. Please see the notice at the top of the repo's README. This is a good thing, fundamentally. :-)
