### ISSUE TITLE
:async sometimes gets trashed before dereference

### ISSUE THREAD

**Issue by mikesperber** [cemerick/clojurescript.test#67]
Running with Nashorn, I the `:async` field in the test environment gets trashed before `finish-test-entry-point' runs. I've had no luck actually navigating the maze of asynchronous execution and mutable state, but replacing the `@(:async ...)` in that function by `(maybe-deref (:async ...))` fixed things for me.

**Comment by cemerick** [comment]
Sorry for the troubles, but I've deprecated this project. Please see the notice at the top of the repo's README. This is a good thing, fundamentally. :-)
