### ISSUE TITLE
Getting ":optimizations :none"  to work

### ISSUE THREAD

**Issue by mike-thompson-day8** [cemerick/clojurescript.test#75]
The project Readme says:
```
clojurescript.test supports all of Google Closure's compilation modes, including :advanced
```

But that's untrue.  This framework does not handle `:optimizations :none`. I tried. It failed.  I researched. I figured out it was impossible.

But if I retreat to, say, `:optimizations :whiteapce` the compile time delays get in the way of a good fast  iterative workflow.  I needed the near-instant compile time speed of `:optimizations :none`  !!

In the end, I worked out a method, which I documented here:   
https://github.com/mike-thompson-day8/cljsbuild-none-test-seed 

Feel free to use the material in there as you see fit.  For example, the repo contains a specific phantomjs runner for this `:none` setting which you may find easy to incorporate.  And the `test.html` will be of interest too, I believe.

I didn't want to produce a patch because I didn't know what (if anything) you'd want to use and how.

**Comment by moea** [comment]
I have a runner I'm using with `none`, if anyone's still interested in having this be supported.

**Comment by martinklepsch** [comment]
@moea definitely share it! :)

**Comment by moea** [comment]
@martinklepsch  https://gist.github.com/moea/ed4d4f428a4cb9905c24

Leaving it as a gist, for now - there's some stuff I'd add in before submitting a PR, to make it behave more like the regular runner (support for addition of arbitrary code/shims, more error checking - I wanted it to be as brief as possible, and don't need those features). 

`nodejs runner-none.js cljsbuild-output-dir cljsbuild-output-file`

**Comment by bensu** [comment]
`:optimizations :none` works now in [doo](https://github.com/bensu/doo)

**Comment by cemerick** [comment]
Sorry for the troubles, but I've deprecated this project. Please see the notice at the top of the repo's README. This is a good thing, fundamentally. :-)
