### ISSUE TITLE
Using slimerjs + casperjs to upload file

### ISSUE THREAD

**Issue by Arko2013** [cemerick/clojurescript.test#83]
Hi folks,

I have been writing automated testscripts for running a web-app using slimerjs + casperjs; that is Casperjs is for the coding and Slimerjs as the engine. I have recently encountered the problem of uploading a file . To be more clear, on clicking the Upload option, a window opens displaying my local File system. I am being unable to gain access to this window through my Automated code. Any help or suggestion regarding this ?

**Comment by cemerick** [comment]
Sorry for the troubles, but I've deprecated this project. Please see the notice at the top of the repo's README. This is a good thing, fundamentally. :-)
