### ISSUE TITLE
No tests ran when requiring any other ns than cemerick.cljs.test

### ISSUE THREAD

**Issue by LiFlash** [cemerick/clojurescript.test#86]
Hi,

I'm writing a reagent app. First of all I had kind of a hard time finding out, that :optimization :none is not working. And now I'm still stuck because when I require the namespace to be tested, zero tests are ran:

ReferenceError: Can't find variable: React

  file:///tmp/runner2773951405978470838.js.html:38350
SyntaxError: Parse error

Ran 0  tests containing 0 assertions.
Testing complete: 0 failures, 0 errors.

If I only require cemerick.cljs.test, the test(s) are ran. Do I need to add react to some externs or something?

Thanks in advance!

**Comment by cemerick** [comment]
I'm not sure what to suggest; I can't think of how that `undefined` error could come out of loading the test ns. If you can publish a repo that reproduces the problem as simply as possible, I might be able to help.

**Comment by LiFlash** [comment]
Hi @cemerick,

I currently had the time to reproduce this issue and set up a 'showcase' repo [here](https://github.com/LiFlash/reagent-dummy).
The important part seems to be the :test-commands in the project.clj. Currently the shim/sham is commented out and the test don't work, with the error message mentioned above. If I uncomment them, everything is fine.
Since the lines
```
"this.literal_js_was_evaluated=true"
 "test/cemerick/cljs/test/extra_test_command_file.js"
```
from your README are meant to be optional, I didn't use them. But your files and the shim/sham combo seem to do something important.
