### ISSUE TITLE
on-testing-complete happens before last :end-test-var

### ISSUE THREAD

**Issue by loganlinn** [cemerick/clojurescript.test#87]
Ran into some unexpected behavior when making an adapter for [Karma test runner](http://karma-runner.github.io). I'm using `:end-test-var` to know when a function test has completed and the `on-testing-complete` callback to let Karma know we're done. With async tests, I'm seeing the complete callback being invoked before the final `:end-test-var` is reported. It seems like it would be fixed if [these two expressions](https://github.com/cemerick/clojurescript.test/blob/2f678c79a5d33aafa12d2d9bd510cd2dacd95ff3/src/cemerick/cljs/test.cljs#L335-L349) were transposed 
or at least update the `(swap! async-test-env ...)` before `(do-report ...)`.

**Comment by cemerick** [comment]
Sorry for the troubles, but I've deprecated this project. Please see the notice at the top of the repo's README. This is a good thing, fundamentally. :-)
