### ISSUE TITLE
cljs.test runner

### ISSUE THREAD

**Issue by cldwalker** [cemerick/clojurescript.test#90]
Hi Chas,
  I'm thinking of writing a small library that emulates :runner but for cljs.test. Are you interested in a pull request that expands your runners to optionally support cljs.test? Alternatively, I could pull the runners out into a library that is agnostic to clojurescript.test and cljs.test. If you're not interested that's cool and I'll probably just make a separate library. I'm thinking of digging into this on friday. Cheers and congrats on the twins!

**Comment by cemerick** [comment]
First, thanks! :-)

I fully expect to cull the CLJS portion of this library once the canonical `cljs.test` can replace it. I've not tried it yet; AFAIK, it doesn't have any async support so far, and of course test runners are an issue (I need an automated workflow from the start, opening HTML pages to load+run compiled tests would be a huge step backwards). I presume the test framework itself will get sorted eventually.

On the other hand, I also presume ClojureScript itself won't sprout N test runner scripts, tooling integration, etc. (It's definitely the (more?) unglamorous side of this JS testing business!) I'm happy to have `cljs.test`-compatible scripts and tooling live here if you and others are willing to contribute it. I'd do it myself, but I'm only shaving absolutely essential yaks these days.

It'd be great if the existing scripts could just fail over to `cljs.test` if `cemerick.cljs.test` isn't available; a fair bit of work has gone into making the scripts work well in different versions of their respective environments, preserving that would be nice. IIRC, the scripts only touch `run-all-tests`, which is part of the original `clojure.test` API, and so hopefully all the names will line up. But, you'll find out quickly one way or the other.

**Comment by cldwalker** [comment]
Great. Will look into this

**Comment by cemerick** [comment]
This is being pushed forward by @bensu, awesome https://github.com/bensu/doo

**Comment by cldwalker** [comment]
Cool. Closing since that solves this issue
