### ISSUE TITLE
Error with preamble

### ISSUE THREAD

**Issue by ducky427** [cemerick/clojurescript.test#91]
Hello,
I am trying to add d3 to a preamble for testing. But if I do, my tests don't run.

I have created a minimal case which demonstrates my problem [here](https://github.com/ducky427/cljd3test). I have tried using both slimerjs and phantomjs to no success.

If I do `lein cljsbuild test`, I get this error:

```
Compiling ClojureScript.
Compiling "target/test.js" from ["src" "test"]...
Successfully compiled "target/test.js" in 2.312 seconds.
Running ClojureScript test: unit-tests
SyntaxError: Parse error

ReferenceError: Can't find variable: cemerick

ERROR: cemerick.cljs.test was not required.

You can resolve this issue by ensuring [cemerick.cljs.test] appears
in the :require clause of your test suite namespaces.
Also make sure that your build has actually included any test files.

Subprocess failed

```
If, however, I remove the preamble on line 31 in [project.clj](https://github.com/ducky427/cljd3test/blob/master/project.clj#L31), tests do run. Output:

```
Compiling ClojureScript.
Running ClojureScript test: unit-tests

Testing d3test-test.core 

Ran 1  tests containing 1 assertions.
Testing complete: 0 failures, 0 errors.
```

I think that the error is due to the fact that d3 uses UTF-8 symbols like symbols for [π,  ε](https://github.com/mbostock/d3/blob/737a9913063ba3d0156555d63e69147284506825/src/math/trigonometry.js#L1) etc and runner.js doesn't seem to define a charset. But I am not sure.

Thanks

**Comment by ducky427** [comment]
I looked into what `runner.js` was doing and I modified it locally to add `<meta charset="utf-8">` to the head of the html generated. But still I got the same error when I ran `phantomjs runner.js target/test.js'

However when I opened by the generated html in firefox, and ran the command `cemerick.cljs.test.run_all_tests()` in the console, I got the tests to run.

Hope this helps.

**Comment by cemerick** [comment]
Thank you for the excellent testcase. Your repo tests properly when using clojurescript.test `0.3.2`, fails with `0.3.3`.

Some recent changes to the phantom/slimerjs test runner to eliminate security context warnings seem to cause another set of problems; here and #88.

I'll dig into it soon. Probably best to just use `0.3.2` in the meantime.

**Comment by ducky427** [comment]
I tested my code with `0.3.2` and it works. Thanks for the suggestion! :+1:

**Comment by cemerick** [comment]
Sorry for the troubles, but I've deprecated this project. Please see the notice at the top of the repo's README. This is a good thing, fundamentally. :-)
