### ISSUE TITLE
Troubles with PhantomJS 2.0 on OSX

### ISSUE THREAD

**Issue by olivergeorge** [cemerick/clojurescript.test#92]
Just wanted to share a quick insight in passing.  Seems like PhantomJS 2.0 on OSX has issues which leads to an inscrutable "Subprocess failed" error.  (2.0 is the new stable as of late Jan)

Switching back to the latest PhantomJS 1.9 release for OSX resolved my issues.

```
$ lein cljsbuild test 
Compiling ClojureScript.
Running ClojureScript test: phantomjs1.9

Testing example.main-test 

Ran 2 synchronous tests containing 2 assertions.
Testing complete: 0 failures, 0 errors.
Waiting on 1 asynchronous test to complete.

Testing example.main-test (async)
Running ClojureScript test: phantomjs2.0
Subprocess failed
```

I forked How-To-Debug-CLJS to get up and running (I was going quite crazy).  If you're curious you can see the code here: https://github.com/olivergeorge/How-To-Debug-CLJS.git

**Comment by cemerick** [comment]
Sorry for the troubles, but I've deprecated this project. Please see the notice at the top of the repo's README. This is a good thing, fundamentally. :-)
