### ISSUE TITLE
Create a Lein plugin that uses cljs.test

### ISSUE THREAD

**Issue by stumitchell** [cemerick/clojurescript.test#94]
Hi I like the work you have done here.

I have been investigating cljs.test and note there is still a lot of boiler plate needed that your lein plugin handles quite well.

So can you adapt your plugin and runners to work with cljs.test as well or create a new plugin that only works with cljs.test??

I will gladly help test this for you.

**Comment by cemerick** [comment]
A few people have suggested exactly this (e.g. @cldwalker via #90).

At some point, I would like to eliminate my port of `clojure.test`; it's suboptimal and overly complex compared to `cljs.test`, due in large part to the lack of certain language-level facilities when I wrote it. This would necessitate porting the runners and Leiningen integration bits.

I'm fairly certain I will do this at some point, though I can't say when. Of course, if someone gets to it first, all the better.

**Comment by cemerick** [comment]
This is being pushed forward by @bensu, awesome https://github.com/bensu/doo

**Comment by cemerick** [comment]
I've deprecated this project. Please see the notice at the top of the repo's README. This is a good thing, fundamentally. :-)
