### ISSUE TITLE
Regression between 0.3.2 and 0.3.3

### ISSUE THREAD

**Issue by j-mckitrick** [cemerick/clojurescript.test#95]
Running my test suite under 0.3.2 passes.

Running it under 0.3.3 fails with this message:

TypeError: 'null' is not an object (evaluating 'a.appendChild')

and can be tracked down to this function used for testing React components:

(defn add-test-div [name]
  (let [doc js/document
        body (.-body js/document)
        div (.createElement doc "div")]
    (.appendChild body div)
    div))

**Comment by jeluard** [comment]
Your code does not look valid according to latest ClojureScript requirements. It should be:

```clojure
(defn add-test
  [div]
  (.appendChild js/body div)
  div))
```

Maybe using `0.3.3` brings a newer ClojureScript that has stricter semantic checks?

**Comment by j-mckitrick** [comment]
@jeluard That's very odd, I cannot reproduce the problem now.  If it reappears, I'll open another issue.  Thanks!
