### ISSUE TITLE
Slimerjs does not work with existing tests

### ISSUE THREAD

**Issue by j-mckitrick** [cemerick/clojurescript.test#96]
Running the test suite under 0.3.3 with slimerjs dropped into as a straight replacement for phantomjs, I get this failure:

Subprocess failed

Here is my cljsbuild test configuration:

:test-commands
     {"client-test" [;;"phantomjs" :runner
                     "slimerjs" :runner
                     "resources/es5-shim.js"
                     "resources/es5-sham.js"
                     "resources/console-polyfill.js"
                     "resources/public/js/client-test.js"]}

**Comment by jeluard** [comment]
Are you using OSX? If yes this is an known [slimerjs issue](https://github.com/laurentj/slimerjs/issues/301).
Installing slimerjs via `brew` fixed the issue for me.

**Comment by cemerick** [comment]
Thanks for picking this up, @jeluard. I didn't know where to start with this one. I don't have easy access to an OS X machine, FWIW.

**Comment by j-mckitrick** [comment]
@jeluard I've make progress after installing via `brew`.  But now I've run into this:

Compiling ClojureScript.
Compiling ClojureScript.
Running ClojureScript test: client-test
Error during the script execution
[Exception] Error: Permission denied to access property "CoffeeScript"  filename:coffee-scripts.js  line:8

Stack trace:
0:@coffee-scripts.js:8:177012
@coffee-scripts.js:8:2

**Comment by jeluard** [comment]
No idea about that one but after some googling it looks related to iframes. It might be a limitation of current implementation of `clojurescript.test`.

**Comment by cemerick** [comment]
Such "security" issues motivated 64459d4efa6d83, which I had hoped resolved the problem. (That will likely get reverted in order to fix #88, but probably won't happen until I [or someone?] does the work to support `:none`.)

@j-mckitrick Where is this `coffee-scripts.js` coming from? It should be getting pulled into the single generated test file.

**Comment by j-mckitrick** [comment]
I have no idea where coffee-scripts.js is coming from.  It only appeared
when I used slimerjs as a runner.

**Comment by cemerick** [comment]
Maybe it's coming from a ClojureScript / CLJSJS dependency?

**Comment by j-mckitrick** [comment]
Hmm, not sure.  The only CLJSJS I have is React.  No coffeescript anywhere.

**Comment by vikeri** [comment]
I had the same issue and it was related to a bug in SlimerJs not playing well with Firefox 37. I downgraded to 36 and it worked.

**Comment by mvd7793** [comment]
@vikeri Thanks for this^. Helped me. :)

**Comment by cemerick** [comment]
Sorry for the troubles, but I've deprecated this project. Please see the notice at the top of the repo's README. This is a good thing, fundamentally. :-)
