### ISSUE TITLE
cljsbuild clean no longer supported

### ISSUE THREAD

**Issue by Engelberg** [cemerick/clojurescript.test#97]
Since cljsbuild clean no longer works, the recommended approach is to add directories to clean to the clean-targets directories in the leiningen profile, so that `lein clean` will be sufficient.

Actually, in most cases, the intermediate files get written to the target directory, which is automatically cleaned by lein clean.

However, in optimizations :none mode, the intermediate files need to be visible to the webserver, which pretty much means they need to go into the resources directory.

A typical :none profile, leveraging the recent :main and :asset-path keys, would look like this:

```clojure
 :cljsbuild {:builds [{:id "none"
                        :source-paths ["src-cljs"]
                        :compiler {:output-to "resources/public/js/main.js",
                                   :output-dir "resources/public/js/out",
                                   :optimizations :none
                                   :main mycode.core
                                   :asset-path "js/out"}}]}
```

So now, by default lein won't clean the output.  This means I need to add "resources/public/js/out" to my clean-targets directory.  But then leiningen complains, because it is considered unsafe to delete files out of the resources directory.  This means you have to add metadata to the clean-targets list of directories which disables this protection.  It makes me squeamish to have to disable this protection on the entire list of clean-targets, because then I get no protection if I inadvertently put in a directory that isn't safe to delete.

Therefore, I have to wonder, why did you get rid of the `lein cljsbuild clean` task?  It seems like cljsbuild knows where it is putting the temporary files, so it knows best where to clean them.  I don't like having to override leiningen's safety feature.

**Comment by cemerick** [comment]
I think you meant to file this under the cljsbuild project? I'll reply here in any case.

`cljsbuild clean` was largely removed because of emezeske/lein-cljsbuild#297. Cleaning derived files / compilation output is just not the job of a plugin; Leiningen has a clean task that works well, and includes good safeguards for not blowing away source files (a _feature_, and why it's refusing to touch your `resources` directory!). Trying to make `cljsbuild clean` similarly safe is wasted when that effort should be concentrated @ `lein clean`.

There are _very_ few cases where one should ever have compilation output or other derived files being placed side-by-side with source files. In the case of `:optimizations :none`, I'd suggest compiling to `target/classes/public/...`; then:

1. The default ring resources-serving middleware will pick it up with no changes or special configuration
2. `lein clean` will work as expected with no additional configuration

**Comment by Engelberg** [comment]
Yes, my mistake, I should have filed on cljsbuild.  Thanks for the response.  I'll try compiling to the target/classes/public directory.  (I note that luminus uses the kind of project file I described above, putting the generated files in the resources directory and turning off protection on clean-targets, so this solution may not be widely known).

**Comment by Engelberg** [comment]
FYI, I was unable to get the ring resources-serving middleware to pick up the files in a subdirectory of target/classes/public, but I'm going to give up for now.

**Comment by cemerick** [comment]
Odd; worksforme. :-| Here's my `:dev :cljsbuild` config:

```clojure
{:builds [{:source-paths ["src/clj" "src/cljs"]
           :compiler {:output-dir "target/classes/public/cljs/"
                      :output-to "target/classes/public/cljs/app.js"
                      :optimizations :none
                      :source-map true
                      :pretty-print true}}]}
```

I then have a `(compojure.route/resources "/")` middleware rolled into my ring routes (all of my static resources are in `resources/public`), and then HTML generated with something equivalent to this (lots of app-specific stuff culled):

```clojure
(GET "/dashboard" req
    (site/template req
      (list [:script {:src "/cljs/goog/base.js"}]
        [:script {:src "/cljs/app.js"}])
      (list 
        [:div#app]
        [:script {:type "text/javascript"} "goog.require('app-ns.dev');"])))
```

**Comment by LiFlash** [comment]
I'm currently struggling with the same issue and your example config still doesn't work for me.
If I understand it correctly, the `(compojure.route/resources "/")` only works for paths on the classpath. I'm not sure if 'target' folder is part of it, but the contained `public` folder seems not to be recognized.

Do you have a project one can look at? There seems to be no complete example of how to use `:optimization :none` with source-maps in the current lib environment for web development...

**Comment by cemerick** [comment]
Sorry, no sample project I can point to, but the configuration bits I quoted above are what I've used in a half-dozen projects. `target/classes` is on the classpath by default, and `resources` is rooted at `public` by default.

**Comment by LiFlash** [comment]
Stupid me, I added `/` to the beginning of the path in the .html file... thanks for your fast reply, so I had another look at it.
Works great! Maybe you can add this to the readme and/or sample projects... would be of great help.
